// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace netflix_eco_back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250520195340_nextepisode")]
    partial class nextepisode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NextEpisode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AirDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "air_date");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "episode_number");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "season_number");

                    b.HasKey("Id");

                    b.ToTable("NextEpisode");

                    b.HasAnnotation("Relational:JsonPropertyName", "next_episode_to_air");
                });

            modelBuilder.Entity("SerieBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiRef")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "apiRef");

                    b.Property<DateTime>("FirstAirDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "first_air_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NextEpisodeToAirId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "original_language");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterPath")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "poster_path");

                    b.Property<int>("SerieId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NextEpisodeToAirId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("SerieBase", b =>
                {
                    b.HasOne("NextEpisode", "NextEpisodeToAir")
                        .WithMany()
                        .HasForeignKey("NextEpisodeToAirId");

                    b.Navigation("NextEpisodeToAir");
                });
#pragma warning restore 612, 618
        }
    }
}
